import type { Product, HeroSlide } from '../types/landing_page_types';

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: '1',
    headline: 'Mastering High-Frequency Trading',
    subheadline: 'A comprehensive architectural breakdown of sub-microsecond execution systems.',
    image: 'https://picsum.photos/id/1/1200/800',
    ctaText: 'Get the Blueprint',
  },
  {
    id: '2',
    headline: 'DeFi Bridge Protocol Security',
    subheadline: 'Post-mortem analysis of the biggest bridge hacks of 2023 and how to prevent them.',
    image: 'https://picsum.photos/id/2/1200/800',
    ctaText: 'Read Case Study',
  },
  {
    id: '3',
    headline: 'Rust for Fintech Engineers',
    subheadline: 'Transitioning from C++ to Rust for mission-critical financial infrastructure.',
    image: 'https://picsum.photos/id/3/1200/800',
    ctaText: 'Start Course',
  },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Global Liquidity Engine',
    author: 'TAJJJR Engineering',
    category: 'Case Study',
    price: 49.00,
    description: 'Deep dive into low-latency execution venues designed for institutional throughput.',
    rating: 4.9,
    reviews: 128,
    image: 'https://picsum.photos/id/20/600/800',
  },
  {
    id: 'p2',
    title: 'Nexus Custody Vault',
    author: 'Security Team',
    category: 'Course',
    price: 129.00,
    description: 'Building multi-signature cold storage solutions with real-time on-chain monitoring.',
    rating: 5.0,
    reviews: 84,
    image: 'https://picsum.photos/id/24/600/800',
  },
  {
    id: 'p3',
    title: 'Event-Driven Architectures',
    author: 'System Arch Team',
    category: 'Guide',
    price: 35.00,
    description: 'Patterns for guarantee idempotency, bulkheads, and backpressure under load.',
    rating: 4.7,
    reviews: 210,
    image: 'https://picsum.photos/id/48/600/800',
  },
  {
    id: 'p4',
    title: 'Microservices at Scale',
    author: 'DevOps Lead',
    category: 'Case Study',
    price: 45.00,
    description: 'Practical breakdown of deploying resilient distributed systems on Kubernetes.',
    rating: 4.8,
    reviews: 156,
    image: 'https://picsum.photos/id/60/600/800',
  },
   {
    id: 'p5',
    title: 'Algorithmic Market Making',
    author: 'Quant Team',
    category: 'Course',
    price: 199.00,
    description: 'Mathematical models and implementation strategies for liquidity provision.',
    rating: 4.9,
    reviews: 302,
    image: 'https://picsum.photos/id/96/600/800',
  },
  {
    id: 'p6',
    title: 'Zero-Knowledge Proofs',
    author: 'Cryptography Unit',
    category: 'Guide',
    price: 59.00,
    description: 'Implementing ZK-SNARKs for privacy-preserving financial transactions.',
    rating: 5.0,
    reviews: 95,
    image: 'https://picsum.photos/id/119/600/800',
  },
  {
    id: 'p7',
    title: 'Advanced Order Types',
    author: 'Trading Systems',
    category: 'Case Study',
    price: 39.00,
    description: 'Implementation details of Iceberg, TWAP, and VWAP execution algorithms.',
    rating: 4.6,
    reviews: 78,
    image: 'https://picsum.photos/id/160/600/800',
  },
  {
    id: 'p8',
    title: 'Low Latency Networking',
    author: 'Infra Team',
    category: 'Course',
    price: 89.00,
    description: 'Kernel bypass, solarflare, and FPGA integration for HFT networks.',
    rating: 4.9,
    reviews: 112,
    image: 'https://picsum.photos/id/180/600/800',
  },
  {
    id: 'p9',
    title: 'Smart Contract Auditing',
    author: 'Security Research',
    category: 'Guide',
    price: 29.00,
    description: 'A checklist and methodology for auditing Solidity contracts for common vulnerabilities.',
    rating: 4.8,
    reviews: 204,
    image: 'https://picsum.photos/id/201/600/800',
  },
  {
    id: 'p10',
    title: 'Exchange Matching Engines',
    author: 'Core Dev',
    category: 'Case Study',
    price: 65.00,
    description: 'Designing deterministic matching engines with LMAX Disruptor patterns.',
    rating: 5.0,
    reviews: 310,
    image: 'https://picsum.photos/id/250/600/800',
  },
  {
    id: 'p11',
    title: 'Distributed Ledger Consensus',
    author: 'R&D',
    category: 'Course',
    price: 150.00,
    description: 'Deep dive into PBFT, Raft, and Proof-of-Stake consensus mechanisms.',
    rating: 4.7,
    reviews: 56,
    image: 'https://picsum.photos/id/366/600/800',
  },
  {
    id: 'p12',
    title: 'Options Pricing Models',
    author: 'Quant Team',
    category: 'Guide',
    price: 45.00,
    description: 'Black-Scholes and Binomial models implemented in Python and C++.',
    rating: 4.8,
    reviews: 134,
    image: 'https://picsum.photos/id/400/600/800',
  },
];
