import type { Product, HeroSlide, PendingReview } from '../types/landing_page_types';

export const PENDING_REVIEWS: PendingReview[] = [
  {
    id: 'pr1',
    productId: 'p3',
    productTitle: 'Event-Driven Architectures',
    productImage: 'https://picsum.photos/id/48/600/800',
    purchaseDate: '2023-11-20',
  },
  {
    id: 'pr2',
    productId: 'p8',
    productTitle: 'Low Latency Networking',
    productImage: 'https://picsum.photos/id/180/600/800',
    purchaseDate: '2023-11-18',
  },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: '1',
    headline: 'Mastering High-Frequency Trading',
    subheadline: 'A comprehensive architectural breakdown of sub-microsecond execution systems.',
    image: 'https://picsum.photos/id/1/1200/800',
    ctaText: 'Get the Blueprint',
  },
  {
    id: '2',
    headline: 'DeFi Bridge Protocol Security',
    subheadline: 'Post-mortem analysis of the biggest bridge hacks of 2023 and how to prevent them.',
    image: 'https://picsum.photos/id/2/1200/800',
    ctaText: 'Read Case Study',
  },
  {
    id: '3',
    headline: 'Rust for Fintech Engineers',
    subheadline: 'Transitioning from C++ to Rust for mission-critical financial infrastructure.',
    image: 'https://picsum.photos/id/3/1200/800',
    ctaText: 'Start Course',
  },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Global Liquidity Engine',
    author: 'TAJJJR Engineering',
    category: 'Case Study',
    price: 49.00,
    description: 'Deep dive into low-latency execution venues designed for institutional throughput.',
    rating: 4.9,
    reviews: 128,
    image: 'https://picsum.photos/id/20/600/800',
    reviewsList: [
      {
        id: 'r1',
        author: 'Sarah Chen',
        rating: 5,
        date: '2023-11-15',
        content: 'Absolutely game-changing. The architectural breakdown helped us reduce our latency by 40%.',
        avatar: 'https://i.pravatar.cc/150?u=1',
      },
      {
        id: 'r2',
        author: 'Michael Ross',
        rating: 5,
        date: '2023-11-10',
        content: 'The depth of detail on the matching engine logic is unmatched. Worth every penny.',
        avatar: 'https://i.pravatar.cc/150?u=2',
      },
      {
        id: 'r3',
        author: 'David Kim',
        rating: 4,
        date: '2023-10-28',
        content: 'Great content, though I wish there were more examples in C++. Still a solid 5/5 for the concepts.',
        avatar: 'https://i.pravatar.cc/150?u=3',
      },
      {
        id: 'r4',
        author: 'Emily White',
        rating: 5,
        date: '2023-10-15',
        content: 'Finally a resource that actually explains the "how" and not just the "what".',
        avatar: 'https://i.pravatar.cc/150?u=4',
      },
      {
        id: 'r5',
        author: 'James Wilson',
        rating: 5,
        date: '2023-10-02',
        content: 'Our team uses this as a reference for our internal training. Highly recommended.',
        avatar: 'https://i.pravatar.cc/150?u=5',
      },
      {
        id: 'r6',
        author: 'Linda Xu',
        rating: 4,
        date: '2023-09-20',
        content: 'Very technical, exactly what I was looking for.',
        avatar: 'https://i.pravatar.cc/150?u=6',
      },
    ],
  },
  {
    id: 'p2',
    title: 'Nexus Custody Vault',
    author: 'Security Team',
    category: 'Course',
    price: 129.00,
    description: 'Building multi-signature cold storage solutions with real-time on-chain monitoring.',
    rating: 5.0,
    reviews: 84,
    image: 'https://picsum.photos/id/24/600/800',
  },
  {
    id: 'p3',
    title: 'Event-Driven Architectures',
    author: 'System Arch Team',
    category: 'Guide',
    price: 35.00,
    description: 'Patterns for guarantee idempotency, bulkheads, and backpressure under load.',
    rating: 4.7,
    reviews: 210,
    image: 'https://picsum.photos/id/48/600/800',
  },
  {
    id: 'p4',
    title: 'Microservices at Scale',
    author: 'DevOps Lead',
    category: 'Case Study',
    price: 45.00,
    description: 'Practical breakdown of deploying resilient distributed systems on Kubernetes.',
    rating: 4.8,
    reviews: 156,
    image: 'https://picsum.photos/id/60/600/800',
  },
  {
    id: 'p5',
    title: 'Algorithmic Market Making',
    author: 'Quant Team',
    category: 'Course',
    price: 199.00,
    description: 'Mathematical models and implementation strategies for liquidity provision.',
    rating: 4.9,
    reviews: 302,
    image: 'https://picsum.photos/id/96/600/800',
  },
  {
    id: 'p6',
    title: 'Zero-Knowledge Proofs',
    author: 'Cryptography Unit',
    category: 'Guide',
    price: 59.00,
    description: 'Implementing ZK-SNARKs for privacy-preserving financial transactions.',
    rating: 5.0,
    reviews: 95,
    image: 'https://picsum.photos/id/119/600/800',
  },
  {
    id: 'p7',
    title: 'Advanced Order Types',
    author: 'Trading Systems',
    category: 'Case Study',
    price: 39.00,
    description: 'Implementation details of Iceberg, TWAP, and VWAP execution algorithms.',
    rating: 4.6,
    reviews: 78,
    image: 'https://picsum.photos/id/160/600/800',
  },
  {
    id: 'p8',
    title: 'Low Latency Networking',
    author: 'Infra Team',
    category: 'Course',
    price: 89.00,
    description: 'Kernel bypass, solarflare, and FPGA integration for HFT networks.',
    rating: 4.9,
    reviews: 112,
    image: 'https://picsum.photos/id/180/600/800',
  },
  {
    id: 'p9',
    title: 'Smart Contract Auditing',
    author: 'Security Research',
    category: 'Guide',
    price: 29.00,
    description: 'A checklist and methodology for auditing Solidity contracts for common vulnerabilities.',
    rating: 4.8,
    reviews: 204,
    image: 'https://picsum.photos/id/201/600/800',
  },
  {
    id: 'p10',
    title: 'Exchange Matching Engines',
    author: 'Core Dev',
    category: 'Case Study',
    price: 65.00,
    description: 'Designing deterministic matching engines with LMAX Disruptor patterns.',
    rating: 5.0,
    reviews: 310,
    image: 'https://picsum.photos/id/250/600/800',
  },
  {
    id: 'p11',
    title: 'Distributed Ledger Consensus',
    author: 'R&D',
    category: 'Course',
    price: 150.00,
    description: 'Deep dive into PBFT, Raft, and Proof-of-Stake consensus mechanisms.',
    rating: 4.7,
    reviews: 56,
    image: 'https://picsum.photos/id/366/600/800',
  },
  {
    id: 'p12',
    title: 'Options Pricing Models',
    author: 'Quant Team',
    category: 'Guide',
    price: 45.00,
    description: 'Black-Scholes and Binomial models implemented in Python and C++.',
    rating: 4.8,
    reviews: 134,
    image: 'https://picsum.photos/id/400/600/800',
  },
];

export const POPULAR_PRODUCTS = ALL_PRODUCTS.slice(0, 4);
