import type { Product, HeroSlide } from '../types/landing_page_types';

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: '1',
    headline: 'Mastering High-Frequency Trading',
    subheadline: 'A comprehensive architectural breakdown of sub-microsecond execution systems.',
    image: 'https://picsum.photos/id/1/1200/800',
    ctaText: 'Get the Blueprint',
  },
  {
    id: '2',
    headline: 'DeFi Bridge Protocol Security',
    subheadline: 'Post-mortem analysis of the biggest bridge hacks of 2023 and how to prevent them.',
    image: 'https://picsum.photos/id/2/1200/800',
    ctaText: 'Read Case Study',
  },
  {
    id: '3',
    headline: 'Rust for Fintech Engineers',
    subheadline: 'Transitioning from C++ to Rust for mission-critical financial infrastructure.',
    image: 'https://picsum.photos/id/3/1200/800',
    ctaText: 'Start Course',
  },
];

export const POPULAR_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Global Liquidity Engine',
    author: 'TAJJJR Engineering',
    category: 'Case Study',
    price: 49.00,
    description: 'Deep dive into low-latency execution venues designed for institutional throughput.',
    rating: 4.9,
    reviews: 128,
    image: 'https://picsum.photos/id/20/600/800',
  },
  {
    id: 'p2',
    title: 'Nexus Custody Vault',
    author: 'Security Team',
    category: 'Course',
    price: 129.00,
    description: 'Building multi-signature cold storage solutions with real-time on-chain monitoring.',
    rating: 5.0,
    reviews: 84,
    image: 'https://picsum.photos/id/24/600/800',
  },
  {
    id: 'p3',
    title: 'Event-Driven Architectures',
    author: 'System Arch Team',
    category: 'Guide',
    price: 35.00,
    description: 'Patterns for guarantee idempotency, bulkheads, and backpressure under load.',
    rating: 4.7,
    reviews: 210,
    image: 'https://picsum.photos/id/48/600/800',
  },
  {
    id: 'p4',
    title: 'Microservices at Scale',
    author: 'DevOps Lead',
    category: 'Case Study',
    price: 45.00,
    description: 'Practical breakdown of deploying resilient distributed systems on Kubernetes.',
    rating: 4.8,
    reviews: 156,
    image: 'https://picsum.photos/id/60/600/800',
  },
   {
    id: 'p5',
    title: 'Algorithmic Market Making',
    author: 'Quant Team',
    category: 'Course',
    price: 199.00,
    description: 'Mathematical models and implementation strategies for liquidity provision.',
    rating: 4.9,
    reviews: 302,
    image: 'https://picsum.photos/id/96/600/800',
  },
  {
    id: 'p6',
    title: 'Zero-Knowledge Proofs',
    author: 'Cryptography Unit',
    category: 'Guide',
    price: 59.00,
    description: 'Implementing ZK-SNARKs for privacy-preserving financial transactions.',
    rating: 5.0,
    reviews: 95,
    image: 'https://picsum.photos/id/119/600/800',
  },
];